DEFRA/trade-imports-data-api

- .config/dotnet-tools.json
- src/Api/Api.csproj
- tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
- tests/Api.IntegrationTests/OpenApi/OpenApiTests.Redoc_VerifyAsExpected.verified.txt
Dependabot cannot do these as they need to be done together but then they also impact tests due to changes.
Performing the upgrade manually in this PR.
> Manual bump of Swashbuckle libs as they need to be done together

- .config/dotnet-tools.json
- Dockerfile
Rather than install latest, use a pinned version of csharpier so we can keep local devs inline with version being used in the pipeline.
> Use local pinned version of csharpier

- Defra.TradeImportsDataApi.sln
- Defra.TradeImportsDataApi.sln.DotSettings
- Dockerfile
- src/Data/Data.csproj
- src/Data/Extensions/ServiceCollectionExtensions.cs
- src/Domain.MongoDB/ClassMapConfiguration.cs
- src/Domain.MongoDB/Domain.MongoDB.csproj
- src/Domain/Domain.csproj
- src/Domain/Gvms/ActualCrossing.cs
- src/Domain/Gvms/CheckedInCrossing.cs
- src/Domain/Gvms/PlannedCrossing.cs
- src/Domain/Ipaffs/Applicant.cs
- src/Domain/Ipaffs/JourneyRiskCategorisationResult.cs
- src/Domain/Ipaffs/LaboratoryTests.cs
- src/Domain/Ipaffs/PartOne.cs
- src/Domain/Ipaffs/RiskAssessmentResult.cs
- src/Domain/Ipaffs/SealCheck.cs
- tests/Api.IntegrationTests/Api.IntegrationTests.csproj
- tests/Api.Tests/Api.Tests.csproj
- tests/Domain.MongoDB.Tests/BsonDateTimeSerializationTests.cs
- tests/Domain.MongoDB.Tests/Domain.MongoDB.Tests.csproj
This is needed so we can use the Domain project independently in things like an API client (as it will need to be published to nuget).
A small tidy of test project references is also included.
> Split Domain from MongoDB references

- .github/workflows/check-pull-request.yml
- .github/workflows/publish.yml
- Makefile
On a PR build and a main build publish the open API spec as a point in time reference. Other teams, such as PHA API owners, can then use the spec as they need.
> Publish open API spec as build artifact

- src/Api/Configuration/ResourceEventOptions.cs
- src/Api/Program.cs
- src/Api/Services/ResourceEventPublisher.cs
- src/Api/appsettings.cdp.dev.json
- src/Api/appsettings.json
- tests/Api.Tests/Services/ResourceEventPublisherTests.cs
We don't appear to have adequate permissions within CDP to list topics and then find the ARN.
> Specify the topic name to be published to directly rather than trying to use discovery on topic name alone

- src/Api/Api.csproj
- tests/Api.IntegrationTests/Api.IntegrationTests.csproj
- tests/Testing/Testing.csproj
Dependabot is currently struggling with AWS 4 part versions and based on our config it's producing a single PR per nuget. Need to change this but for now, it's being done manually.
> Update to latest versions

- src/Api/Services/ResourceEventExtensions.cs
- tests/Api.Tests/Services/ResourceEventExtensionsTests.cs
This PR fixes an issue introduced in PR https://github.com/DEFRA/trade-imports-data-api/pull/56.
When a child of child property was the only field reported in the change set, the sub resource type was not being set as the logic to resolve it was incorrect.
We now split on `/`, remove empty entries and then take the first.
> Ensure sub resource type resolved when child of child properties are being updated

- src/Api.Client/Api.Client.csproj
- src/Api.Client/CustomsDeclarationResponse.cs
- src/Api/Endpoints/CustomsDeclarations/CustomsDeclarationResponse.cs
- src/Api/Endpoints/CustomsDeclarations/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Services/ResourceEventExtensions.cs
- src/Api/Services/ResourceEventPublisher.cs
- src/Api/appsettings.Development.json
- src/Data/Entities/CustomsDeclarationEntity.cs
- src/Domain/CustomsDeclaration/CustomsDeclaration.cs
- src/Domain/CustomsDeclaration/InboundError.cs
- src/Domain/CustomsDeclaration/InboundErrorItem.cs
- src/Domain/CustomsDeclaration/InboundErrorNotification.cs
- src/Domain/Domain.csproj
- src/Domain/Events/ResourceEventSubResourceTypes.cs
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/GetTests.GetCustomsDeclaration_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/GetTests.cs
- tests/Api.Client.Tests/Endpoints/ImportPreNotifications/GetCustomsDeclarationsTests.GetCustomDeclarationsByChed_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.Get_WhenFound_ShouldReturnContent.verified.txt
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.cs
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests_DomainExample.json
- tests/Api.Tests/Endpoints/Gmrs/GetTests.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetCustomsDeclarationsByChedIdTests.Get_WhenFound_ShouldReturnContent.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
- tests/Api.Tests/Services/ResourceEventExtensionsTests.cs
- tests/Api.Tests/Services/ResourceEventPublisherTests.cs
This PR adds support for inbound errors stored against the customs declaration.
Domain structure is as follows:
```c#
public class InboundError
{
[JsonPropertyName("notifications")]
public InboundErrorNotification[]? Notifications { get; set; }
}
public class InboundErrorNotification
{
[JsonPropertyName("externalCorrelationId")]
public string? ExternalCorrelationId { get; set; }
[JsonPropertyName("externalVersion")]
public int? ExternalVersion { get; set; }
[JsonPropertyName("errors")]
public InboundErrorNotificationItem[]? Errors { get; set; }
}
public class InboundErrorNotificationItem
{
[JsonPropertyName("code")]
public string? Code { get; set; }
[JsonPropertyName("message")]
public string? Message { get; set; }
}
```
~~Update to a pre release of version 0.10.0 of the API client and …
> Add new InboundError type off the CustomsDeclaration

- src/Api/Services/CustomsDeclarationService.cs
- src/Api/Services/ImportPreNotificationService.cs
- tests/Api.Tests/Services/CustomsDeclarationServiceTests.cs
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
We saw in testing that sub resource type is not being set on entity creation. Sub resource type is set during change set creation therefore produce a change set on entity creation too.
For now, we don't know for definite if we want to do this long term but for now it seems reasonable.
> Include a change set one entity creation, which will then set the sub resource type

- src/Api/Services/CustomsDeclarationService.cs
The inbound error was missing from the data object that is used to determine the change set and therefore the sub resource type of the data event being raised.
This PR adds it in.
> Add inbound error to change set data

- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
- src/Domain/Errors/ErrorNotification.cs
- tests/Api.Tests/Api.Tests.csproj
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests_DomainExample.json
- tests/Api.Tests/Endpoints/ProcessingErrors/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/ProcessingErrors/GetTests_DomainExample.json
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
Allows a generic error to be saved or input from another system that we want to capture, such as messages from CDS.
> Add nullable message for generic error if needed

- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
- src/Domain/Errors/ErrorNotification.cs
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests_DomainExample.json
- tests/Api.Tests/Endpoints/ProcessingErrors/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/ProcessingErrors/GetTests_DomainExample.json
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
During testing, it was hard to see what the created date for error notifications was if there were multiple for the same version. Beyond the correlation ID, a created date would help.
This PR adds just that!
> Add created date for error notification

- .github/dependabot.yml
Second attempt for dependabot and AWS SDK.
> Change group so it's all AWS SDK as previous update type was not valid

- Directory.Build.props
- src/Api/Api.csproj
- src/Data/Data.csproj
- tests/Api.Client.Tests/Api.Client.Tests.csproj
- tests/Api.IntegrationTests/Api.IntegrationTests.csproj
- tests/Api.IntegrationTests/Endpoints/CustomsDeclarationTests.cs
- tests/Api.IntegrationTests/Endpoints/ImportPreNotificationTests.cs
- tests/Api.IntegrationTests/Endpoints/ProcessingErrorTests.cs
- tests/Api.IntegrationTests/Endpoints/SqsTestBase.cs
- tests/Api.Tests/Api.Tests.csproj
- tests/Data.Tests/Data.Tests.csproj
- tests/Domain.Tests/Domain.Tests.csproj
- tests/Testing/Testing.csproj
Dependabot is missing some updates and not sure why. These changes bring the service as up to date as possible.
I saw a failure initially in both the pipeline and locally when running integration tests. Messages could not be drained quick enough, hence the additional diagnostic logs and setting the receive message params so things happen quicker.
> Update dependencies where possible - v4 of AWS cannot be used yet as MongoDB.Driver.Authentication.AWS is still tracking a v3 transient dependency

- compose.yml
- src/Api/Endpoints/CustomsDeclarations/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/Gmrs/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ProcessingErrors/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/Search/EndpointRouteBuilderExtensions.cs
- src/Api/Program.cs
- tests/Api.IntegrationTests/IntegrationTestBase.cs
ASPNETCORE_ENVIRONMENT previously drove auth being enabled. This was temporary and is an unclear side effect of running the service locally in Docker in DEVELOPMENT mode.
This PR therefore removes the behaviour so auth is active all the time, as it should be.
> Remove disable of auth based on running DEVELOPMENT mode

- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
- src/Domain/Ipaffs/Commodities.cs
- src/Domain/Ipaffs/CommodityCheck.cs
- src/Domain/Ipaffs/CommodityComplement.cs
- src/Domain/Ipaffs/ComplementParameterSet.cs
- src/Domain/Ipaffs/ImportPreNotification.cs
- src/Domain/Ipaffs/PartOne.cs
- src/Domain/Ipaffs/PartTwo.cs
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/GetImportPreNotificationsTests.GetCustomsDeclaration_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/ImportPreNotifications/GetTests.GetImportPreNotification_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/RelatedImportDeclarations/GetTests.WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests.Get_WhenFound_ShouldReturnContent.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests_DomainExample.json
- tests/Api.Tests/Endpoints/Search/RelatedImportDeclarationsTests.Search_WhenFound_ShouldReturnContent.verified.txt
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
A choice was made in the past to change the schema which deviated from Ipaffs, creating confusion.
This brings it more closely in line.
> CDMS-654: Update schema to more closely match Ipaffs

- src/Api/Services/DataEntityExtensions.cs
- src/Api/Services/ImportPreNotificationService.cs
- tests/Api.Tests/Services/DataEntityExtensionsTests.cs
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
The IPAFFS data is too large at times for us to emit the resource and the change set. We need to look at extended storage formats if we are to produce messages that include such data for IPAFFS.
Therefore, for now, do not include the resource and change set for import pre notification messages.
> Do not include resource and change set for IPAFFS entity inserts/updates

- src/Api/Program.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
Previously, `nullable = true` was being included despite the code declaring that it couldn't be.
> Support nullable types when generating docs

- src/Api/Services/GmrService.cs
- tests/Api.IntegrationTests/Endpoints/ImportPreNotificationTests.cs
- tests/Testing/ImportPreNotificationIdGenerator.cs
I noticed a Mongo error around the nullability I wasn't able to reliably reproduce.  This adds in the nullability checks for safety.
The tests are also improved to create a new ID each time the test is ran.
> CDMS-658: Add nullable check to the Gmr query and improve tests

- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ImportPreNotifications/ImportPreNotificationUpdateResponse.cs
- src/Api/Endpoints/ImportPreNotifications/ImportPreNotificationUpdatesRequest.cs
- src/Api/Endpoints/ImportPreNotifications/ImportPreNotificationUpdatesResponse.cs
- src/Api/Program.cs
- src/Api/Services/IImportPreNotificationService.cs
- src/Api/Services/ImportPreNotificationService.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.Get_WhenInvalidRequest_ShouldBeBadRequest.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.Get_WhenValidRequest_ShouldReturnSingle.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
- tests/Testing/EndpointFilter.cs
- tests/Testing/EndpointQuery.cs
- tests/Testing/Endpoints.cs
As the endpoint will only be notification reference number and an updated date, I decided to create a path away from the existing notifications one.
Consumers will call `/import-pre-notification-updates` with a from and to date as query params (for now).
Only dummy data is returned currently, in order to get approval on the endpoint structure.
> Add initial scaffolding for notification updates endpoint

- src/Data/Entities/CustomsDeclarationEntity.cs
During local testing of a different problem, it was observed that we have repetition for the same values in our identifiers list. Amend the code by performing a distinct. Also prevent empty strings as this is technically possible due to the current `GetDocumentReferenceIdentifier` implementation.
> Prevent duplicate values in identifiers list

- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Services/GmrService.cs
- src/Api/Services/IImportPreNotificationService.cs
- src/Api/Services/ImportPreNotificationService.cs
- src/Api/Services/ImportPreNotificationUpdate.cs
- src/Data/Entities/GmrEntity.cs
- src/Data/Mongo/MongoIndexService.cs
- tests/Api.IntegrationTests/IntegrationTestBase.cs
- tests/Api.IntegrationTests/Services/ImportPreNotificationServiceTests.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.cs
Query for notifications translates to:
```
db.getCollection("ImportPreNotificationEntity").aggregate(
[
{
"$match" : {
"updated" : {
"$gte" : ISODate("2025-05-20T15:59:59.000+0000"),
"$lt" : ISODate("2025-05-20T16:00:01.000+0000")
}
}
}, 
{
"$project" : {
"referenceNumber" : "$_id",
"updated" : "$updated",
"_id" : 0.0
}
}
]
);
```
This uses the index on the Updated field of the notification.
This is part one of bringing in changes from original work in PR https://github.com/DEFRA/trade-imports-data-api/pull/117 that was reverted.
> Add filtering of notifications by from and to value against .Updated field

- src/Api/Data/CustomsDeclarationRepository.cs
- src/Api/Data/GmrRepository.cs
- src/Api/Data/ICustomsDeclarationRepository.cs
- src/Api/Data/IGmrRepository.cs
- src/Api/Data/IImportPreNotificationRepository.cs
- src/Api/Data/IProcessingErrorRepository.cs
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Data/ImportPreNotificationUpdate.cs
- src/Api/Data/ProcessingErrorRepository.cs
- src/Api/Program.cs
- src/Api/Services/CustomsDeclarationService.cs
- src/Api/Services/GmrService.cs
- src/Api/Services/ICustomsDeclarationService.cs
- src/Api/Services/IGmrService.cs
- src/Api/Services/IImportPreNotificationService.cs
- src/Api/Services/ImportPreNotificationService.cs
- src/Api/Services/ProcessingErrorService.cs
- src/Api/Services/RelatedImportDeclarationsService.cs
- src/Data/Extensions/QueryableExtensions.cs
- tests/Api.IntegrationTests/Services/ImportPreNotificationServiceTests.cs
- tests/Api.Tests/Data/CustomsDeclarationRepositoryTests.cs
- tests/Api.Tests/Data/GmrRepositoryTests.cs
- tests/Api.Tests/Data/ImportPreNotificationRepositoryTests.cs
- tests/Api.Tests/Data/ProcessingErrorRepositoryTests.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.cs
- tests/Api.Tests/Services/CustomsDeclarationServiceTests.cs
- tests/Api.Tests/Services/GmrServiceTests.cs
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
- tests/Api.Tests/Services/ProcessingErrorServiceTests.cs
- tests/Api.Tests/Services/RelatedImportDeclarationsServiceTests.cs
During work on notification updates, there was friction working around the current use of the `IDbContext` in our services and other places in the codebase.
This made refactoring harder than it needed to be.
We have also got a relatively busy `IDbContext` implementation with methods that have come over from previous codebases and are now not used.
In implementing a repository layer, we get:
- Specific methods for retrieval of certain types of data
- We can minimise the data being requested from the DB in a more controlled manner
- We can reuse methods that were starting to be repeated
- We can protect our services in tests and mock any repositories
- We can test our repositories in integration tests instead
- We can refactor our repositories without affecting our logic/tests for services …
> Introduce repository layer so we can encapsulate data reading/writing

- src/Data/ConcurrencyException.cs
- src/Data/Mongo/MongoDbContext.cs
- tests/Api.IntegrationTests/Endpoints/ImportPreNotificationUpdateTests.cs
- tests/Api.IntegrationTests/Endpoints/RelatedImportDeclarationsTests.cs
The main premise of the data API is for consumers to manage what exists and what doesn't exist and then act accordingly. If something does not exist then it should be created, however if two processes are checking for existence at the same time then they will both conclude nothing exists so they need to create it; which will result in a failure to write for one of the processes.
This is where our retry model within the consumer will kick in, therefore mitigating the failure to write first time around within the data API. And it will succeed on the second attempt as an update and not an insert.
In these scenarios, the data API is therefore handling concurrency issues and it should not write the problem as an unhandled exception. It's a known side effect of the consumption/write model we …
> MongoDB exceptions that should be concurrency errors

- src/Api/Services/ResourceEventPublisher.cs
- tests/Api.Tests/Services/ResourceEventPublisherTests.cs
This PR will allow consumers to log in a generic way, which will then show the ID of the resource being consumed.
> Add ResourceId as message header

- src/Api/Data/IImportPreNotificationRepository.cs
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Data/ImportPreNotificationUpdateQuery.cs
- src/Api/Data/ImportPreNotificationUpdates.cs
- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ImportPreNotifications/ImportPreNotificationUpdatesRequest.cs
- src/Api/Endpoints/ImportPreNotifications/ImportPreNotificationUpdatesResponse.cs
- src/Api/Services/IImportPreNotificationService.cs
- src/Api/Services/ImportPreNotificationService.cs
- src/Data/Mongo/MongoIndexService.cs
- tests/Api.IntegrationTests/Endpoints/ImportPreNotificationUpdateTests.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.Get_WhenInvalidRequest_PageLessThan1_ShouldBeBadRequest.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.Get_WhenInvalidRequest_PageSizeLessThan1_ShouldBeBadRequest.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.Get_WhenValidRequest_ShouldReturnSingle.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
- tests/Testing/EndpointFilter.cs
This PR includes paging when looking for updates to CHEDs and related data that might be linked to the CHED.
The max page size has not been decided yet so currently it's unbounded.
> Add pagination to notification updates endpoint

- compose.yml
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Metrics/EmfExporter.cs
- src/Api/appsettings.IntegrationTests.json
- src/Data/Entities/ImportPreNotificationUpdateEntity.cs
- src/Data/Mongo/MongoIndexService.cs
- tests/Api.IntegrationTests/Endpoints/ImportPreNotificationUpdateTests.cs
A problem with the previous implementation was highlighted when paging comes into play. As the update entity was itself being updated if it existed already, it was technically possible for notifications to appear as if they were moving pages; if, for example, an update for the notification came in at the same time as a series of pages of updates being requested.
Therefore we now switch to an update document that is created once for a given notification ID. It cannot change therefore it can never appear to move pages. If an update for the same notification is handled, a new update document will be created.
When requesting the data, it's grouped by notification ID and the latest updated field from the source reference is returned.
Also included is a metrics change whereby metrics cannot be …
> Change notification "updates" tracking so a document is created on each update so events stay immutable

- src/Api/appsettings.Development.json
- src/Api/appsettings.cdp.dev.json
- src/Data/Extensions/ServiceCollectionExtensions.cs
- src/Data/MongoDbOptions.cs
Turned on in development and also the CDP dev environment, include logging of any queries being made so we can trace anything that looks incorrect.
This also facilitated confirming the following query used the index regardless of search casing:
```
db.getCollection("CustomsDeclaration").aggregate(
[{ "$match" : { "clearanceRequest.declarationUcr" : { "$regularExpression" : { "pattern" : "^21b8f085d58b42fbb81ce47c8c2ff503-ducr1$", "options" : "is" } } } }]
)
```
```
{
"explainVersion" : "1",
"queryPlanner" : {
"namespace" : "trade-imports-data-api.CustomsDeclaration",
"indexFilterSet" : false,
"parsedQuery" : {
"clearanceRequest.declarationUcr" : {
"$regex" : "^21b8f085d58b42fbb81ce47c8c2ff503-ducr1$",
"$options" : "is"
}
},
"queryHash" : "7AD8F36D",
"planCacheKey" : "415138B4", …
```
> Add basic mongo query logging for development

- src/Api/Metrics/MetricsMiddleware.cs
- src/Api/Metrics/RequestMetrics.cs
We have seen some paths make it into our request logs that we are not interested in, therefore we start to ignore paths in this PR.
> Ignore certain paths for request metrics if they start with specific values

- src/Api/Data/CustomsDeclarationRepository.cs
- src/Api/Data/GmrRepository.cs
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Data/ProcessingErrorRepository.cs
We have observed several Mongo queries where it's looking for an empty array or similar. Therefore, there is no reason to call Mongo if we don't expect to find anything.
As such, this PR adds some defensive checks so we bail early in methods if there is nothing to find.
> Add defensive checks so we don't query Mongo if we don't have to

- src/Api/Data/CustomsDeclarationRepository.cs
- src/Api/Data/GmrRepository.cs
- src/Api/Data/ICustomsDeclarationRepository.cs
- src/Api/Data/IGmrRepository.cs
- src/Api/Data/IImportPreNotificationRepository.cs
- src/Api/Data/IProcessingErrorRepository.cs
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Data/ProcessingErrorRepository.cs
- src/Api/Services/CustomsDeclarationService.cs
- src/Api/Services/DataEntityExtensions.cs
- src/Api/Services/GmrService.cs
- src/Api/Services/ImportPreNotificationService.cs
- src/Api/Services/ProcessingErrorService.cs
- src/Data/IDbContext.cs
- src/Data/IMongoCollectionSet.cs
- src/Data/Mongo/MongoCollectionSet.cs
- src/Data/Mongo/MongoDbContext.cs
- tests/Api.IntegrationTests/Endpoints/CustomsDeclarationTests.cs
- tests/Api.Tests/Services/CustomsDeclarationServiceTests.cs
- tests/Api.Tests/Services/GmrServiceTests.cs
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
- tests/Api.Tests/Services/ProcessingErrorServiceTests.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryCollectionSet.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryDbContext.cs
In order to protect the state of our data, we are now prohibiting persistence if the write to SNS does not succeed.
Now the behaviour risk is flipped as we might experience a failure to commit a transaction after the SNS write has taken place OR the event could be consumed before the transaction has written.
The latter should be unlikely as the default transaction isolation is read uncommitted. We save first and then we write to SNS, so data will be written on save. Should the SNS write fail, the transaction will not be committed but we might have had reads during the period between save and SNS failure. Do we care?
We could look at changing the transaction isolation level to prevent dirty reads but we move more towards consuming before data is committed. Which in turn moves us more …
> CDMS-917: Ensure data is not persisted if the resource event for certain entities cannot be written to SNS

- .github/workflows/check-pull-request.yml
- Dockerfile
- src/Api/Api.csproj
- tests/Api.Tests/OpenApi/OpenApiTests.Redoc_VerifyAsExpected.verified.txt
~Have been seeing builds hanging over last couple of days in what seems to always be Vacuum. Therefore, trying the latest version.~
The Dockerfile build output was hanging around the Vacuum step, therefore initially thought it was something there. Updated Vacuum version, Swashbuckle for openapi.json generation and associated snapshot test.
In the end it looked like the Github actions stdout out limit was being met resulting in the build step hanging and not just truncating the log as it has been seen to do in the past. Therefore, we now run Vacuum without full details and just report on errors.
This problem is a bit of worry longer term but for now we can get past it.
> CDMS-917: Reduce output during Dockerfile build to avoid Github actions build step hanging

- src/Api/Data/CustomsDeclarationRepository.cs
- src/Api/Data/GmrRepository.cs
- src/Api/Data/ICustomsDeclarationRepository.cs
- src/Api/Data/IGmrRepository.cs
- src/Api/Data/IImportPreNotificationRepository.cs
- src/Api/Data/IProcessingErrorRepository.cs
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Data/ProcessingErrorRepository.cs
- src/Api/Services/CustomsDeclarationService.cs
- src/Api/Services/DataEntityExtensions.cs
- src/Api/Services/GmrService.cs
- src/Api/Services/ImportPreNotificationService.cs
- src/Api/Services/ProcessingErrorService.cs
- src/Data/IDbContext.cs
- src/Data/IMongoCollectionSet.cs
- src/Data/Mongo/MongoCollectionSet.cs
- src/Data/Mongo/MongoDbContext.cs
- tests/Api.IntegrationTests/Endpoints/CustomsDeclarationTests.cs
- tests/Api.Tests/Services/CustomsDeclarationServiceTests.cs
- tests/Api.Tests/Services/GmrServiceTests.cs
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
- tests/Api.Tests/Services/ProcessingErrorServiceTests.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryCollectionSet.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryDbContext.cs
Reverts DEFRA/trade-imports-data-api#198
I want to revert this and introduce more tests for the resource events being raised, then the changes in this PR will be added back in to show now functional change from the state already in prod.
> Revert "CDMS-917: Ensure data is not persisted if the resource event for certain entities cannot be written to SNS"

- src/Data/Extensions/MongoClientSettingsExtensions.cs
- src/Data/Extensions/ServiceCollectionExtensions.cs
- tests/Api.IntegrationTests/IntegrationTestBase.cs
Please see `UsePrimaryMajorityConsistency` method being added and where it's used.
We see continual examples, albeit potentially small, where updates are made to the data API yet when data is requested, the stale previous version is returned.
These settings aim to combat that problem as we want the data API to always return whatever data has been accepted during a write.
> CDMS-1040: Change default read write settings coming from the connection string that will apply globally for all of the API
