- .github/workflows/publish.yml
> Add missing write permission for packages build from main

- compose.yml
- src/Api/appsettings.Development.json
- src/Data/Data.csproj
- src/Data/Extensions/ServiceCollectionExtensions.cs
Updated Compose file to use a replica set, and updated connection string to use direct connection locally
> Add AWS Auth for MongoDb Driver so it can connect on CDP

- src/Api/Health/WebApplicationExtensions.cs
Health check all endpoint was not showing anything. The predicate was wrong.
> Invert predicate so all checks are included

- src/Api/appsettings.json
> Use async console logger for improved performance

- src/Api.Client/Api.Client.csproj
- src/Api.Client/CustomsDeclarationResponse.cs
- src/Api.Client/Endpoints.cs
- src/Api.Client/GmrResponse.cs
- src/Api.Client/ITradeImportsDataApiClient.cs
- src/Api.Client/TradeImportsDataApiClient.cs
- src/Api/Domain/Gmr.cs
- src/Api/Endpoints/CustomsDeclarations/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/Gmrs/EndpointRouteBuilderExtensions.cs
- src/Domain/CustomsDeclaration/ClearanceDecision.cs
- src/Domain/Domain.csproj
- src/Domain/Json/UnknownTimeZoneDateTimeJsonConverter.cs
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/GetTests.GetCustomsDeclaration_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/GetTests.cs
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/PutTests.cs
- tests/Api.Client.Tests/Endpoints/Gmrs/GetTests.GetGmr_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/Gmrs/GetTests.cs
- tests/Api.Client.Tests/Endpoints/Gmrs/PutTests.cs
- tests/Api.IntegrationTests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
This PR extends the client to support CDS and GVMS data endpoints.
> Add GMRs and customs declarations to the client

- src/Data/Data.csproj
> Remove ref as referenced in repo wide Directory.Build.props

- src/Api.Client/Api.Client.csproj
- src/Domain/CustomsDeclaration/ClearanceDecision.cs
- src/Domain/Domain.csproj
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests_DomainExample.json
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
> Added source version to ClearanceDecision

- src/Api/appsettings.json
> Add Developer client

- src/Api/Services/CustomsDeclarationService.cs
- src/Api/Services/DataEntityExtensions.cs
- tests/Api.Tests/Services/DataEntityExtensionsTests.cs
> Refactor resource event extensions into data entity extensions, which should have been the responsibility of the methods

- src/Api/Endpoints/Search/RelatedImportDeclarationsRequest.cs
- src/Api/Services/RelatedImportDeclarationsService.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
- tests/Api.Tests/Services/RelatedImportDeclarationsServiceTests.cs
Adds loading indirect links, up to a specified depth, which defaults to 3
> Added in indirect link with a configurable depth

- src/Api.Client/Api.Client.csproj
- src/Api.Client/Endpoints.cs
- src/Api.Client/ITradeImportsDataApiClient.cs
- src/Api.Client/RelatedImportDeclarationsRequest.cs
- src/Api.Client/RelatedImportDeclarationsResponse.cs
- src/Api.Client/TradeImportsDataApiClient.cs
- src/Api/Services/RelatedImportDeclarationsService.cs
- tests/Api.Client.Tests/Endpoints/RelatedImportDeclarations/GetTests.GetProcessingError_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/RelatedImportDeclarations/GetTests.WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/RelatedImportDeclarations/GetTests.cs
- tests/Api.IntegrationTests/Endpoints/RelatedImportDeclarationsTests.cs
- tests/Api.Tests/Services/RelatedImportDeclarationsServiceTests.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryCollectionSet.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryCollectionSetExtensions.cs
- tests/Api.Tests/Utils/InMemoryData/MemoryDbContext.cs
added api client tests and integration tests
> Related Import Declaration Searching

- src/Api/OpenApi/PossibleValueSchemaFilter.cs
- src/Domain/Ipaffs/ConsignmentCheck.cs
- src/Domain/Ipaffs/ImportPreNotification.cs
- src/Domain/Ipaffs/PartOne.cs
- src/Domain/Ipaffs/Purpose.cs
- tests/Api.Client.Tests/Endpoints/CustomsDeclarations/GetImportPreNotificationsTests.GetCustomsDeclaration_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/ImportPreNotifications/GetTests.GetImportPreNotification_WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Client.Tests/Endpoints/RelatedImportDeclarations/GetTests.WhenFound_ShouldNotBeNull.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests.Get_WhenFound_ShouldReturnContent.verified.txt
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests_DomainExample.json
- tests/Api.Tests/Endpoints/Search/RelatedImportDeclarationsTests.Search_WhenFound_ShouldReturnContent.verified.txt
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
Updated the Ipaffs Schema to the latest version.
> CDMS-634: Update Ipaffs Schema

- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
The Api has been updated with the new Ipaffs fields.
> CDMS-634: Bump Api Client version

- src/Api/Health/ServiceCollectionExtensions.cs
- src/Api/Health/SnsHealthCheck.cs
- src/Api/Health/SnsHealthCheckBuilderExtensions.cs
- src/Api/appsettings.cdp.test.json
- tests/Api.IntegrationTests/Health/HealthTests.cs
> Add ARN prefix for CDP test and a health check for the SNS topic

- src/Api.Client/Api.Client.csproj
- src/Data/Extensions/ServiceCollectionExtensions.cs
- src/Domain/CustomsDeclaration/ClearanceDecisionCheck.cs
- src/Domain/Domain.csproj
- tests/Api.Tests/Endpoints/CustomsDeclarations/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
> removed department code from decision check

- Defra.TradeImportsDataApi.sln.DotSettings
- src/Api.Client/Endpoints.cs
- src/Api/Endpoints/Search/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/Search/RelatedImportDeclarationsRequest.cs
- src/Api/Services/RelatedImportDeclarationsService.cs
- src/Data/Mongo/MongoCollectionSet.cs
- tests/Api.IntegrationTests/Endpoints/RelatedImportDeclarationsTests.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
> Address current sonar issues

- tests/Api.IntegrationTests/ImportPreNotificationFixtures.cs
> Declare options once outside consumption

- src/Api/Endpoints/CustomsDeclarations/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/Gmrs/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ProcessingErrors/EndpointRouteBuilderExtensions.cs
- src/Api/appsettings.Development.json
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
> Amend docs and add local run settings

- src/Api/Data/IImportPreNotificationRepository.cs
- src/Api/Data/ImportPreNotificationRepository.cs
- src/Api/Endpoints/ImportPreNotifications/EndpointRouteBuilderExtensions.cs
- src/Api/Endpoints/ImportPreNotifications/ImportPreNotificationUpdatesRequest.cs
- src/Api/Services/IImportPreNotificationService.cs
- src/Api/Services/ImportPreNotificationService.cs
- tests/Api.IntegrationTests/Endpoints/ImportPreNotificationUpdateTests.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetUpdatesTests.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/ImportPreNotificationUpdatesRequestTests.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
- tests/Testing/EndpointFilter.cs
When looking for updates, allow a NOT in filter on status so not all status values need to be known.
> Add excludeStatus so a NOT IN can be performed when looking for updates

- src/Api/Services/ImportPreNotificationService.cs
- tests/Api.Tests/Services/ImportPreNotificationServiceTests.cs
Now are zipping large messages and can handle unzipping them, we can now emit the full IPAFFS message detail.
> Include IPAFFS entity as resource

- src/Data/Mongo/MongoCollectionSet.cs
- src/Data/Mongo/MongoIndexService.cs
- tests/Api.IntegrationTests/IntegrationTestBase.cs
Because apparently we don't want it.
> CDMS-727: Remove Entity suffix from collection names

- compose.yml
- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
- src/Domain/Ipaffs/Commodities.cs
- src/Domain/Ipaffs/CommodityComplements.cs
- src/Domain/Ipaffs/ComplementParameterSets.cs
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests.Get_WhenReturningDomainExample_ShouldBeCorrectJson.verified.json
- tests/Api.Tests/Endpoints/ImportPreNotifications/GetTests_DomainExample.json
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
This renames some classes and fields to conform with the other naming conventions.
> CDMS-743: Rename some classes/fields

- src/Api/Authentication/BasicAuthenticationHandler.cs
- src/Api/OpenApi/ServiceCollectionExtensions.cs
- src/Api/OpenApi/WebApplicationExtensions.cs
- src/Api/Program.cs
- src/Api/Services/ResourceEventPublisher.cs
- src/Api/Utils/Logging/WebApplicationBuilderExtensions.cs
This PR covers the following PRs:
- PR https://github.com/DEFRA/trade-imports-processor/pull/124
- PR https://github.com/DEFRA/trade-imports-processor/pull/126
- PR https://github.com/DEFRA/trade-imports-processor/pull/127
- PR https://github.com/DEFRA/trade-imports-processor/pull/137
Also covered is a check of the logs being made to ensure no PII and all pertinent information is included.
Some logic from the `Program.cs` has been moved to extension classes and some removed as it was duplicated.
> Replicate logging work from the processor and gateway

- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
> Incremented the version number for the nuget packages

- src/Api/Services/RelatedImportDeclarationsService.cs
- src/Domain/CustomsDeclaration/ChedReferenceRegexes.cs
- tests/Api.Tests/Services/RelatedImportDeclarationsServiceTests.cs
Updated the search endpoint to make use of the regex, so it can work with split consignments
> Update Search endpoint

- src/Api.Client/Api.Client.csproj
- src/Domain/Domain.csproj
- src/Domain/Ipaffs/Decision.cs
- tests/Api.Tests/OpenApi/OpenApiTests.OpenApi_VerifyAsExpected.verified.txt
There is also "Acceptable for Non Internal Market".
> CDMS-894: Add new ConsignmentDecision possible value

- Directory.Build.props
- src/Api.Client/Api.Client.csproj
- src/Api/Api.csproj
- src/Data/Data.csproj
- tests/Api.Client.Tests/Api.Client.Tests.csproj
- tests/Api.IntegrationTests/Api.IntegrationTests.csproj
- tests/Api.Tests/Api.Tests.csproj
- tests/Data.Tests/Data.Tests.csproj
- tests/Domain.Tests/Domain.Tests.csproj
- tests/Testing/Testing.csproj
This change updates the dependencies to the latest where possible.
> CDMS-951: Update dependencies

- src/Api/appsettings.json
Secrets in CDP will be removed manually.
> Remove gateway user no longer required
